[package]
name = "tcl2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
serde_json = "1.0.68"
structopt = "0.3.25"
ctrlc = "3.2.1"
